# Change these first
owner: robpc # Your GitHub organization or username, where this repository lives
repo: bluesky-feeds-status # The name of this repository

assignees:
  - robpc

sites:
  - name: Bluesky Feeds
    url: https://feeds.skyblue.social/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Bluesky Feeds Status for @robpc.com"
  introTitle: "Bluesky Feeds Status for @robpc.com"
  introMessage: Uptime for all Bluesky feeds created by @robpc.com
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
